# __Introduction to NumPy__

## __Agenda__

In this lesson, we will cover the following concepts with the help of examples:

- Fundamentals of NumPy
  * Advantages of NumPy
  * NumPy: Installation and Import
- NumPy: Array Object
  * Creating NumPy Arrays

## __1. Fundamentals of NumPy__

NumPy (Numerical Python) is a free and open-source library that is mostly used for mathematical operations in scientific and engineering applications.

- It is a Python library used for working with arrays.
- It consists of a multidimensional array of objects and a collection of functions for manipulating them.
- It conducts mathematical and logical operations on arrays.

**Note:** The array object in NumPy is called ndarray.

### __1.1  Advantages of NumPy__
- It provides an array object that is faster than traditional Python lists.
- It provides supporting functions.
- Arrays are frequently used in data science.
- NumPy arrays are stored in one continuous place in memory, unlike lists.

### __1.2 NumPy: Installation and Import__
- `C:\Users\Your Name>pip install numpy` command is used to install NumPy.
- NumPy is imported under the name np like `import numpy as np`

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

## __2. NumPy: Array Object__
A NumPy ndarray object can be created by using the array() function.

In [3]:
arr = np.array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]


In [4]:
print(type(arr))

<class 'numpy.ndarray'>


In [5]:
arr2 = [23,34,56]
print(type(arr2))

<class 'list'>


In [6]:
arr2_new = np.array(arr2)
print(type(arr2_new))

<class 'numpy.ndarray'>


In [8]:
print(arr2_new)

[23 34 56]


### __2.1 Creating NumPy Arrays__
- Create multiple dimensional arrays, such as 0D, 1D, 2D and 3D

In [9]:
# Create a 0D Array
arr0 = np.array(24)
print ('0D array is', arr0)

0D array is 24


In [10]:
# Create a 1D Array
arr1 = np.array([1,2,3,4])
print ('1D array is', arr1)

1D array is [1 2 3 4]


In [11]:
# Create a 2D Array
arr1 = np.array([[1,2,3,4], [5,6,7,8]])
print ('2D array is', arr1)

2D array is [[1 2 3 4]
 [5 6 7 8]]


In [12]:
# Create a 3D Array
arr3 = np.array([[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]]])
print ('3D array is', arr3)

3D array is [[[1 1 1]
  [2 2 2]]

 [[3 3 3]
  [4 4 4]]]


# __Attributes and Functions in Python__

## __Agenda__
In this lesson, we will cover the following concepts with the help of examples:

- Attributes of NumPy Arrays
  * Explanation of Attributes
- NumPy Array Functions

## __1. Attributes of NumPy Arrays__ ##

Few common attributes of NumPy array:

![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_03_NumPy/2_Attributes_and_Functions_in_Python/Image_1.png)

In [13]:
arr = np.array([[1,2,3],[4,2,5]])

In [14]:
print("No. of dimensions: ", arr.ndim)

No. of dimensions:  2


In [15]:
print("Shape of array: ", arr.shape)

Shape of array:  (2, 3)


In [16]:
print("Size of array: ", arr.size)

Size of array:  6


In [17]:
print("Array stores elements of type: ", arr.dtype)

Array stores elements of type:  int32


In [18]:
print("Length of one array element in bytes: ", arr.itemsize)

Length of one array element in bytes:  4


In [19]:
print("Array's data: ", arr.data)

Array's data:  <memory at 0x000001B78615FAC0>


### __1.1 Explanation of Attributes:__ ###
- `ndarray.ndim`: It is the number of axes (dimensions) of the array.

![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_03_NumPy/2_Attributes_and_Functions_in_Python/Image_2.png)

- `ndarray.shape`: It provides the size of the array for each dimension. The output data type is a tuple.

![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_03_NumPy/2_Attributes_and_Functions_in_Python/Image_3.png)

- `ndarray.size` : It is the total number of elements in the array.

![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_03_NumPy/2_Attributes_and_Functions_in_Python/Image_4.png)

- `ndarray.dtype`: It shows the data type of the elements in the array.

![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_03_NumPy/2_Attributes_and_Functions_in_Python/Image_5.png)

- `ndarray.itemsize`: It shows the length of one array element in bytes.

![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_03_NumPy/2_Attributes_and_Functions_in_Python/IMage_6.png)

- `ndarray.data`: It is an attribute offering direct access to the raw memory of a NumPy array.

## __2. NumPy Array Functions__ ##
![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_03_NumPy/2_Attributes_and_Functions_in_Python/Image_7.png)

- `ndarray.reshape`: It is used to reshape (new shape) the current elements of an array.

In [28]:
# Example: Converting a 1D Array to a 2D Array
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(3,4)
print(newarr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [26]:
# Converting a multidimensional(3D) array into a 1D array
arr3D = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
flattened_array = arr3D.flatten()
print(flattened_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [27]:
# Let's create a 2D array for the transpose example
arr2D = np.array([[1, 2, 3], [4, 5, 6]])
# Transposing the 2D array
transposed_array = arr2D.transpose()
print(transposed_array)

[[1 4]
 [2 5]
 [3 6]]


## __Assisted Practice__

### __Problem Statement:__

As a data scientist, your task is to create a Python project that explores NumPy arrays' attributes and functions. This project will deepen your understanding of NumPy arrays, including accessing their attributes and performing common operations using NumPy functions. Use the dataset containing daily temperature records for a week.

temperatures = [ 75.2, 77.1, 74.5, 79.3, 82.6, 81.2, 77.8 ]


**Steps to Perform:**

1. Explore the key attributes of NumPy arrays, including `ndim`, `shape`, `size`, `dtype`, `itemsize`, and `data`.
2. Demonstrate important NumPy array functions such as `reshape`, `flatten`, and `transpose`.

In [29]:

# Step 1: Create a NumPy array from the dataset
temperatures = np.array([75.2, 77.1, 74.5, 79.3, 82.6, 81.2, 77.8])

In [36]:
# Step 2: Explore key attributes of the NumPy array
print("--- Attributes of the NumPy Array ---")
print("Number of dimensions: ", temperatures.ndim)
print("Shape of array: ", temperatures.shape)
print(" Size of array: ", temperatures.size)
print("Type of array: ", temperatures.dtype)
print("Itemsize of array: ", temperatures.itemsize)
print("Reshaping of array: ", temperatures.reshape(1,7))

--- Attributes of the NumPy Array ---
Number of dimensions:  1
Shape of array:  (7,)
 Size of array:  7
Type of array:  float64
Itemsize of array:  8
Reshaping of array:  [[75.2 77.1 74.5 79.3 82.6 81.2 77.8]]


# __NumPy Arithmetic Statistical and String Functions__

## __Agenda__

In this lesson, we will cover the following concepts with the help of examples:
- Arithmetic Operations Using NumPy
  * Addition
  * Subtraction
  * Multiplication
  * Division
  * Power of
- Statistical Function in Numpy
  * Calculating Median, Mean, Standard Deviation, and Variance in the Array
  * Calculating Percentiles
- String Function in Numpy

## __1. Arithmetic Operations Using NumPy__ ##
### __1.1 Addition__ ###

In [40]:
a = np.array([30,20,10])
b = np.array([20,90,10])
result = np.add(a,b)
print(result)

[ 50 110  20]


### __1.2 Subtraction__ ###

In [38]:
a = np.array([[30,40,60], [50,70,90]])
b = np.array([[10,20,30], [40,30,80]])
result = np.subtract(a,b)
print(result)

[[20 20 30]
 [10 40 10]]


# Heading
## Sub Heading
### Sub sub heading
#### one more
##### one moremore

### __1.3 Multiplication__ ###

In [41]:
# Perform element-wise multiplication of two arrays using the 'np.multiply' method
a = np.array([30,20,10])
b = np.array([10,20,30])
result = np.multiply(a,b)
print(result)

[300 400 300]


### __1.4 Division__ ###

In [49]:
# Perform element-wise division of two arrays using the 'np.divide' method
a = np.array([[1,2,1],[2,2,3]])
b = np.array([[3,4,5],[4,5,6]])
result = np.divide(a,b)
print(result)

[[0.33333333 0.5        0.2       ]
 [0.5        0.4        0.5       ]]


### __1.5 Power of__ ###

In [47]:
# Perform element-wise power operation where each element in 'a' is raised to the corresponding element in 'b' using the 'np.power' method
a = [2,2,2,2,2]
b = [2,3,4,5,6]
c = np.power(a,b)
print(c)

[ 4  8 16 32 64]


In [48]:
print(type(c))

<class 'numpy.ndarray'>


In [50]:
a = 4.5
type(a)

float

In [52]:
a = int(a)
print(type(a))

<class 'int'>


In [53]:
print(a)

4


In [54]:
b = 4
print(type(b))

<class 'int'>


In [55]:
b = float(b)
print(b)

4.0


## __2. Statistical Function in Numpy__ ##
### __2.1 Calculating Median, Mean, Standard Deviation, and Variance in the Array__ ###

In [56]:
# Median
array = np.array([[4,3,2],[10,1,0],[5,8,24]])
print(np.median(array))

4.0


In [57]:
print(np.mean(array))

6.333333333333333


In [58]:
print(np.std(array))

6.944222218666553


In [59]:
np.var(array)

48.22222222222222

### __2.2 Calculating Percentiles__ ###
- The `np.percentile()` function is used to compute the nth percentile of the array elements.
- The nth percentile value should be in between 0 and 100.

In [67]:
np.percentile(array,50)

4.0

## __3. String Function in Numpy__ ##

In [69]:
# Perform element-wise string concatenation for two arrays of string
x = np.array(['Hello', 'World'])
y = np.array(['Welcome', 'Learners'])
result = np.char.add(x,y)
print(result)

['HelloWelcome' 'WorldLearners']


In [70]:
x = ['Hello', 'World']
y = ['Welcome', 'Learners']
x+y

['Hello', 'World', 'Welcome', 'Learners']

In [71]:
# Replacing the old substring with the new substring
str = "Hello How are you"
print(str)

Hello How are you


In [72]:
z = np.char.replace(str,'Hello', 'Hi')
print(z)

Hi How are you


In [73]:
# Converting all lowercase characters in a string to uppercase and vice-versa
str1 = "hello how are you"
print(str1)

hello how are you


In [74]:
z = np.char.upper(str1)
print(z)

HELLO HOW ARE YOU


In [75]:
str2 = "GREETINGS OF THE DAY"
print(str2)

GREETINGS OF THE DAY


In [76]:
s = np.char.lower(str2)
print(s)

greetings of the day


## __Assisted Practice__

### __Problem Statement:__

Consider the following arrays:

- Arrays for Arithmetic Operations:
  * Array A: [15, 25, 35, 45, 55]
  * Array B: [5, 10, 15, 20, 25]

- Array for Statistical Operations:
  * Array C: [12, 22, 32, 42, 52, 62, 72, 82, 92, 102]

- Arrays for String Functions:
  * String Array X: ['Hello', 'Data', 'Science', 'Class', 'Learners']
  * String Array Y: ['World', 'Analysis', 'is', 'Fun', '2023']
  
  
__Steps to Perform:__

1. Perform element-wise addition, subtraction, multiplication, division, and power operations on Arrays A and B
2. Calculate the median, mean, standard deviation, and variance for Array C
3. Concatenate corresponding elements of String Arrays X and Y
4. Convert all elements in String Array X to uppercase
5. Replace a specific substring in String Array Y with another substring

In [77]:
a = np.array([15,25,35,45,55])
b = np.array([5,10,15,20,25])
add = np.add(a,b)
print(add)

[20 35 50 65 80]


In [78]:
print(np.subtract(a,b))

[10 15 20 25 30]


In [79]:
print(np.multiply(a,b))

[  75  250  525  900 1375]


In [80]:
print(np.divide(a,b))

[3.         2.5        2.33333333 2.25       2.2       ]


In [81]:
print(np.power(a,b))

[     759375  1977800241 -2091638453 -1924594607   447042167]


In [82]:
c = np.array( [12, 22, 32, 42, 52, 62, 72, 82, 92, 102])
print(np.mean(c))

57.0


In [83]:
np.median(c)

57.0

In [84]:
np.std(c)

28.722813232690143

In [85]:
np.var(c)

825.0

In [86]:
x = np.array( ['Hello', 'Data', 'Science', 'Class', 'Learners'])
y = np.array(['World', 'Analysis', 'is', 'Fun', '2023'])

In [87]:
print(np.char.add(x,y))

['HelloWorld' 'DataAnalysis' 'Scienceis' 'ClassFun' 'Learners2023']


In [89]:
print(np.char.upper(y))

['WORLD' 'ANALYSIS' 'IS' 'FUN' '2023']


In [91]:
print(np.char.replace(y, '2023', '2025'))

['World' 'Analysis' 'is' 'Fun' '2025']


# __Indexing__

## __Agenda__
In this lesson, we will cover the following concepts with the help of examples:

- NumPy Array Indexing
  * Access Elements in the 1D NumPy Array
  * Access Elements in the 2D NumPy Array
  * Access Elements in 3D NumPy Array
  * Negative Indexing

## __1. NumPy Array Indexing__ ##
NumPy indexing allows you to access an array element using an index value, which begins from 0.

![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_03_NumPy/4_Indexing/Image_1.png)

In [ ]:
# Let's create 1D, 2D and 3D NumPy arrays:
import numpy as np
array_1d = np.array([1,2,3,4,5,6])
array_2d = np.array([[1,2,3],[4,5,6]])
array_3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

### __1.1 Access Elements in the 1D NumPy Array__ ###

In [ ]:
print(array_1d[3])

4


In [ ]:
print(array_1d[7])

IndexError: index 7 is out of bounds for axis 0 with size 6

In [ ]:
print(array_1d[1] + array_1d[0])

3


### __1.2 Access Elements in the 2D NumPy Array__
Consider a 2D array as a table, with dimensions as rows and indexes as columns.

![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_03_NumPy/4_Indexing/Image_2.png)

In [ ]:
array_2d = np.array([[1,2,3],[4,5,6]])
print(array_2d)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(array_2d[0,2])

3


In [ ]:
print(array_2d[1,1])

5


### __1.3 Access Elements in 3D NumPy Array__ ###
- [x,y,z] corresponds to xth element, yth row, and zth column.

In [ ]:
array_3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [ ]:
print(array_3d[1,1,0])

10


In [ ]:
print(array_3d[0,1,2])

6


### __1.4 Negative Indexing__

- Negative indices are counted from the end of an array.
- In a negative indexing system, the last element will be the first element with an index of -1, the second last element with an index of -2, and so on.

In [ ]:
# Let's create 1D, 2D and 3D NumPy arrays:
import numpy as np
array_1d = np.array([1,2,3,4,5,6])
array_2d = np.array([[1,2,3],[4,5,6]])
array_3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [ ]:
print(array_1d[-3])

4


In [ ]:
print(array_2d[1,-1])

6


In [ ]:
print(array_3d[1,1,-1])

12


## __Assisted Practice__

### __Problem Statement:__

1. Create a 1D NumPy array with at least 10 elements
2. Create a 2D NumPy array with a minimum of 3 rows and 4 columns
3. Create a 3D NumPy array with at least 2 matrices, each containing 2 rows and 3 columns
4. Accessing Elements in Arrays
5. Access and print various elements from 1D, 2D, and, 3D using positive indexing
6. Perform and print some basic arithmetic operations (like addition, subtraction) using elements accessed from 1D, 2D, and, 3D arrays
7. Access and print elements using negative indices in all three arrays

In [ ]:
# Create a 1D NumPy array with at least 10 elements
array_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Create a 2D NumPy array with a minimum of 3 rows and 4 columns
array_2d = np.array([[11, 12, 13, 14], [15, 16, 17, 18], [19, 20, 21, 22]])

# Create a 3D NumPy array with at least 2 matrices, each containing 2 rows and 3 columns
array_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

4 as positive index
6 as negative index

In [ ]:
print(array_1d[3])

4


In [ ]:
print(array_1d[-5])

6


#### 2d array = 15 from positive index and 19 from negative index

In [ ]:
print(array_2d[1,0])

15


In [ ]:
print(array_2d[-1,-4])

19


#### 3d array = 5 from positive index and 3 from negative index

In [ ]:
print(array_3d[0,1,1])

5


In [ ]:
print(array_3d[-2,-2,-1])

3


In [ ]:
import numpy as np

array_3d = np.array([[[1, 2, 3], [4, 5, 6]], 
                      [[7, 8, 9], [10, 11, 12]]])

# Print positions (indices) of all elements
for index in np.ndindex(array_3d.shape):
    print(f"Position: {index}, Value: {array_3d[index]}")


Position: (0, 0, 0), Value: 1
Position: (0, 0, 1), Value: 2
Position: (0, 0, 2), Value: 3
Position: (0, 1, 0), Value: 4
Position: (0, 1, 1), Value: 5
Position: (0, 1, 2), Value: 6
Position: (1, 0, 0), Value: 7
Position: (1, 0, 1), Value: 8
Position: (1, 0, 2), Value: 9
Position: (1, 1, 0), Value: 10
Position: (1, 1, 1), Value: 11
Position: (1, 1, 2), Value: 12


# __Slicing__

## __Agenda__
In this lesson, we will cover the following concepts with the help of examples:

- NumPy Array Slicing
  * Slicing 1D NumPy Arrays
  * Slicing Using Step Value
  * Slicing: 2D Array
  * Slicing: 3D Array
  * Negative Slicing

## __1. NumPy Array Slicing__

- In Python, slicing refers to moving elements from one index to another.
- Instead of using an index, the slice is passed as **[start:end]**.
- Another way to pass the slice is to add a step as **[start:end:step]**.
- In slicing, if the starting is not passed, it is considered as 0. If the step is not passed as 1 and if the end is not passed, it is considered as the length of the array in that dimension.

In [ ]:
Employee_rating = np.array([1, 4, 3, 5, 6, 8, 9, 10, 12])

In [ ]:
print(Employee_rating[1:7])

[4 3 5 6 8 9]


In [ ]:
Books = np.array(['Physics','DataScience','Maths','Python','Hadoop', 'OPPs', 'Java', 'Cloud'])

In [ ]:
print(Books[5:])

['OPPs' 'Java' 'Cloud']


In [ ]:
print(Books[:3])

['Physics' 'DataScience' 'Maths']


### __1.2 Slicing Using Step Value__

In [ ]:
X = np.array([8, 7, 6, 5, 4, 3, 2, 1])
print(X[1:6:3])

[7 4]


In [ ]:
print(X[2::2])

[6 4 2]


### Negative slicing

In [ ]:
Neg_slice = np.array([13, 34, 58, 69, 44, 56, 37,24])

In [ ]:
print(Neg_slice[:-1])

[13 34 58 69 44 56 37]


In [ ]:
print(Neg_slice[:-3])

[13 34 58 69 44]
